[project]
name = "pantheon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fitz>=0.0.1.dev2",
    "mistralai>=1.8.1",
    "pillow>=11.2.1",
    "pymupdf>=1.26.0",
    "send2trash>=1.8.3",
    "wxpython>=4.2.3",
]
